### ISSUE TITLE
Sans serif font for images

### ISSUE THREAD

**Issue by markjmeredith** [ibm-cloud-docs/enterprise-account-architecture#2]
Hi! Can we use IBM's sans serif font for the images? It seems a bit strange to have a different font in the diagrams than in the rest of the content in the screens for docs in this topic.

**Comment by jenschlot** [comment]
Hi @markjmeredith can you let us know what browser you were using? Thanks!

**Comment by markjmeredith** [comment]
Sure can! I’m using Chrome.

From: Jenifer Schlotfeldt ***@***.***>
Date: Wednesday, May 17, 2023 at 3:02 PM
To: ibm-cloud-docs/enterprise-account-architecture ***@***.***>
Cc: Mark Meredith1 ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [ibm-cloud-docs/enterprise-account-architecture] Sans serif font for images (Issue #2)
Hi @markjmeredith can you let us know what browser you were using? Thanks! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: <ibm-cloud-docs/enterprise-account-architecture/issues/2/1551974498@ github. com>
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

Hi @markjmeredith<https://github.com/markjmeredith> can you let us know what browser you were using? Thanks!

**Comment by jenschlot** [comment]
Thanks! Transferred this defect over to the doc app development team.
